version: '3.8'
services:
  db:
    image: postgres
    container_name: db-link
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres1234
    volumes:
      - /mnt/postgres/ulink:/var/lib/postgresql/data

  api:
    build: ./server
    container_name: api-link
    env_file:
      - ./server/.env
    ports:
      - '3000:3000'
    depends_on:
      - db

  app:
    build: ./dashboard
    container_name: app-link
    ports:
      - '8080:8080'

  # mongo:
  #   image: mongo:4.2
  #   restart: always
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: 1234
  #   ports: 
  #     - '27017:27017'
