# Use root/example as user/password credentials
version: '3.1'

services:
  api:
    build: .
    #command: sh -c "npx prisma db push && yarn start:dev"
    container_name: api-link
    env_file:
      - .env
    ports:
      - '3000:3000'
    volumes:
      - .:/home/app/server/
      - /home/app/server/node_modules/
volumes:
  app:
    driver: local
