# Use root/example as user/password credentials
version: '3.1'

services:
  api:
    build: .
    container_name: api-link
    env_file:
      - .env
    ports:
      - '3000:3000'

  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 1234
    volumes:
      - /tmp/database:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    